spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/firstdb
    username: postgres
    password: 16032005
    hikari:
      maximum-pool-size: 50
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 9090
